[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm ci --only=production']

[phases.build]
cmds = ['cd frontend && npm ci && npm run build']

[start]
cmd = 'cd backend && node src/server.js'
