name: 🐛 Bug Report
description: Report a bug or accessibility issue
title: "[Bug]: "
labels: ["bug", "accessibility"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: screen-reader
    attributes:
      label: 🗣️ Screen Reader
      description: Which screen reader were you using?
      options:
        - NVDA
        - JAWS
        - VoiceOver (macOS)
        - VoiceOver (iOS)
        - TalkBack (Android)
        - Orca (Linux)
        - Other
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser were you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g., Chrome 120.0.6099.71
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: 📱 Device Type
      description: What device were you using?
      options:
        - Desktop
        - Mobile
        - Tablet
        - Other
    validations:
      required: true

  - type: textarea
    id: accessibility-impact
    attributes:
      label: ♿ Accessibility Impact
      description: How does this bug affect accessibility? (e.g., screen reader can't read content, keyboard navigation broken, etc.)
      placeholder: Describe the accessibility impact...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: testing
    attributes:
      label: 🧪 Testing Checklist
      description: Please check what you've tested
      options:
        - label: Tested with screen reader
          required: true
        - label: Tested keyboard navigation
          required: true
        - label: Tested with high contrast mode
        - label: Tested with zoom up to 200%
        - label: Tested on mobile device
